name: auto-build
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        name: "setup node"
        with:
          node-version: "18"
      - uses: actions/upload-pages-artifact
      - run: npm i
      - run: npm run deploy
